// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLzGyPUrgQPH7ImAnS5eq_qm3fln24NOc',
    appId: '1:218627526229:web:633fd873e1e951951e0edc',
    messagingSenderId: '218627526229',
    projectId: 'finsage-7c0a2',
    authDomain: 'finsage-7c0a2.firebaseapp.com',
    storageBucket: 'finsage-7c0a2.firebasestorage.app',
    measurementId: 'G-B0DH48F7K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLzGyPUrgQPH7ImAnS5eq_qm3fln24NOc',
    appId: '1:218627526229:android:33fc4cf47fa744261e0edc',
    messagingSenderId: '218627526229',
    projectId: 'finsage-7c0a2',
    storageBucket: 'finsage-7c0a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLzGyPUrgQPH7ImAnS5eq_qm3fln24NOc',
    appId: '1:218627526229:ios:cef168b26c22f5d01e0edc',
    messagingSenderId: '218627526229',
    projectId: 'finsage-7c0a2',
    storageBucket: 'finsage-7c0a2.firebasestorage.app',
    iosBundleId: 'com.example.finsageUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLzGyPUrgQPH7ImAnS5eq_qm3fln24NOc',
    appId: '1:218627526229:ios:cef168b26c22f5d01e0edc',
    messagingSenderId: '218627526229',
    projectId: 'finsage-7c0a2',
    storageBucket: 'finsage-7c0a2.firebasestorage.app',
    iosBundleId: 'com.example.finsageUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLzGyPUrgQPH7ImAnS5eq_qm3fln24NOc',
    appId: '1:218627526229:web:43d2865b0c3ddd241e0edc',
    messagingSenderId: '218627526229',
    projectId: 'finsage-7c0a2',
    authDomain: 'finsage-7c0a2.firebaseapp.com',
    storageBucket: 'finsage-7c0a2.firebasestorage.app',
    measurementId: 'G-2RQLSZKZRB',
  );
}
